[package]
name = "futarchy-amm-jup-sdk"
description = "SDK for interacting with Futarchy AMM, built for Jupiter"
license = "BUSL-1.1"
version = "0.1.2"
edition = "2024"

[dependencies]
jupiter-amm-interface = { version = ">=1.0.0-beta.0, <2" }
anchor-lang = "1.0.0"
anyhow = "1.0.99"
rust_decimal = "1.37.2"
